# Generated by Django 6.0.1 on 2026-02-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_appointment_doctor_remove_appointment_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
